language: c
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
branches:
  only:
    - experimental
matrix:
  exclude:
    - os: osx
      compiller: gcc
      
before_install:
  - git submodule update --init --recursive

env:
  - OPTIONS="-DCMAKE_BUILD_TYPE=Release"

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update >/dev/null && sudo apt-get -q install cmake; fi

script:  
  - mkdir build
  - cd build
  - cmake ../ $OPTIONS
  - make
  
