language: c
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
before_install:
  - git submodule update --init --recursive
env:
  - OPTIONS="-DCMAKE_BUILD_TYPE=Release"
install:
  - sudo apt-get update >/dev/null
  - sudo apt-get -q install cmake
script:  
  - mkdir build
  - cd build
  - cmake ../ $OPTIONS
  - make
  